- name: Install python virtualenv
  apt: name=python-virtualenv state=present update_cache=yes
  become: True

- name: Install python pip
  apt: name=python-pip state=present update_cache=yes
  become: True

- name: Install git
  apt: name=git state=present update_cache=yes
  become: True

- name: Install unzip
  apt: name=unzip state=present update_cache=yes
  become: True